[parity]
chain = "pos-contracts/spec.json"
base_path = "parity-data/node3"

[ui]
disable = true

[network]
port = 30303

[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_set", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
port = 8543

[websockets]
disable = true

[ipc]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[account]
unlock = ["0x190ec582090ae24284989af812f6b2c93f768ecd"]
password = ["config/password"]

[mining]
force_sealing = true
min_gas_price = 1000000000
engine_signer = "0x190ec582090ae24284989af812f6b2c93f768ecd"
reseal_on_txs = "none"
